/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Modules',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'modules' }],
    },
  ],
};

module.exports = sidebars;
